version: '3.3'

services:
  firefly:
    image: fireflyiii/core:latest
    container_name: fireflyiii
    env_file: .env
    volumes:
      - ./upload:/var/www/html/storage/upload
    ports:
      - 127.0.0.1:8888:8080
    depends_on:
      - db
    secrets:
      - app_key
    restart: unless-stopped

  db:
    image: mariadb
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
volumes:
   firefly_iii_upload:
   firefly_iii_db:

secrets:
  app_key:
    file: ./app_key
