version: '3.3'

services:
  firefly:
    image: fireflyiii/core:latest
    container_name: firefly
    env_file: .env
    volumes:
      - ./upload:/var/www/html/storage/upload
    ports:
      - 127.0.0.1:8888:8080
    depends_on:
      - db
    secrets:
      - app_key
      - mysql_user
      - mysql_password
    restart: unless-stopped

  db:
    image: mariadb
    container_name: fireflydb
    hostname: fireflyiiidb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER_FILE=/run/secrets/mysql_user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE=firefly
    volumes:
      - ./db:/var/lib/mysql
    secrets:
      - mysql_user
      - mysql_password
    restart: unless-stopped

secrets:
  app_key:
    file: ./app_key # Generate using: openssl rand -base64 32
  mysql_user:
    file: ./mysql_user
  mysql_password:
    file: ./mysql_password # Generate using: openssl rand -base64 48
