version: '3.3'

services:
  firefly:
    image: fireflyiii/core:latest
    container_name: fireflyiii
    env_file: .env
    volumes:
      - ./upload:/var/www/html/storage/upload
    ports:
      - 127.0.0.1:8888:8080
    depends_on:
      - db
    secrets:
      - app_key
    restart: unless-stopped

  db:
    image: mariadb
    container_name: fireflydb
    hostname: fireflyiiidb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD_FILE=/run/secrets/fireflydb_password
      - MYSQL_DATABASE=firefly
    volumes:
      - ./db:/var/lib/mysql
    secrets:
      - fireflydb_password
    restart: unless-stopped

secrets:
  app_key:
    file: ./app_key # Generate using: openssl rand -base64 48
  fireflydb_password:
    file: ./fireflydb_password # Generate using: openssl rand -base64 48
